### ISSUE TITLE
VGG_S finetune

### ISSUE THREAD

**Issue by PeterPan1990** [jimgoo/caffe-oxford102#2]
Hi, 
  Thanks for sharing the experiments info, I was wondering that if could give me a link to pretrained-weight for VGG_S finetune part?

**Comment by jimgoo** [comment]
Here's a snapshot at 20K iterations:

https://s3.amazonaws.com/jgoode/oxford102_VGG_S_iter_20000.caffemodel

which gives

```
1108 15:07:57.676288  1699 solver.cpp:266] Iteration 20000, Testing net (#0)
I1108 15:08:55.986631  1699 solver.cpp:315]     Test net output #0: accuracy = 0.827742
I1108 15:08:56.456195  1699 solver.cpp:189] Iteration 20000, loss = 0.00186366
I1108 15:08:56.456280  1699 solver.cpp:464] Iteration 20000, lr = 0.0001
```
